/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalresourcesystem;

import javax.swing.JOptionPane;

/**
 *
 * @author yanyanchen
 */
public class HospitalAdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form HospitalAdminHomePage
     */
    public HospitalAdminHomePage() {
        initComponents();
    }
    
    public HospitalAdminHomePage(String email) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePatient = new javax.swing.JButton();
        btnCreateHospital = new javax.swing.JButton();
        btnViewDoctor = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();
        btnViewHospital = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreatePatient.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCreatePatient.setText("Create Patient");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreatePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 286, 54));

        btnCreateHospital.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCreateHospital.setText("Create Hospital");
        btnCreateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 286, 55));

        btnViewDoctor.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnViewDoctor.setText("View Upadate & Delete Doctor");
        btnViewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, 55));

        btnViewPatient.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnViewPatient.setText("View Update & Delete Patient");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 286, 54));

        btnViewHospital.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnViewHospital.setText("View Update & Delete Hospital");
        btnViewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, 55));

        btnCreateDoctor.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCreateDoctor.setText("Create Doctor");
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 286, 55));

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 280, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateDeleteDoctor in=new CreateDeleteDoctor();
        in.setVisible(true);

    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void btnViewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewUpdateDeleteHospital in=new ViewUpdateDeleteHospital();
        in.setVisible(true);
    }//GEN-LAST:event_btnViewHospitalActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewUpdateDeletePatient in=new ViewUpdateDeletePatient();
        in.setVisible(true);
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewUpdateDeleteDoctor in=new ViewUpdateDeleteDoctor();
        in.setVisible(true);
    }//GEN-LAST:event_btnViewDoctorActionPerformed

    private void btnCreateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHospitalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateDeleteHospital in=new CreateDeleteHospital();
        in.setVisible(true);
    }//GEN-LAST:event_btnCreateHospitalActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateDeletePatient in=new CreateDeletePatient();
        in.setVisible(true);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Index().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalAdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreateHospital;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnViewDoctor;
    private javax.swing.JButton btnViewHospital;
    private javax.swing.JButton btnViewPatient;
    // End of variables declaration//GEN-END:variables
}
