/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalresourcesystem;

import javax.swing.JOptionPane;

/**
 *
 * @author yanyanchen
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnHospitalAdminLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnCommunityAdminLogin = new javax.swing.JButton();
        BtnDoctorLogin = new javax.swing.JButton();
        BtnSystemAdminLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnPatientLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        BtnHospitalAdminLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnHospitalAdminLogin.setForeground(new java.awt.Color(0, 102, 153));
        BtnHospitalAdminLogin.setText("HOSPITAL ADMIN");
        BtnHospitalAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHospitalAdminLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnHospitalAdminLogin);
        BtnHospitalAdminLogin.setBounds(330, 480, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1070, 320, 120, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/community.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 320, 130, 160);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 320, 130, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hospital.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 320, 130, 160);

        BtnCommunityAdminLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnCommunityAdminLogin.setForeground(new java.awt.Color(0, 102, 153));
        BtnCommunityAdminLogin.setText("COMMUNITY ADMIN");
        BtnCommunityAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCommunityAdminLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCommunityAdminLogin);
        BtnCommunityAdminLogin.setBounds(580, 480, 200, 50);

        BtnDoctorLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnDoctorLogin.setForeground(new java.awt.Color(0, 102, 153));
        BtnDoctorLogin.setText("DOCTOR");
        BtnDoctorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoctorLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDoctorLogin);
        BtnDoctorLogin.setBounds(1060, 480, 130, 50);

        BtnSystemAdminLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnSystemAdminLogin.setForeground(new java.awt.Color(0, 102, 153));
        BtnSystemAdminLogin.setText("ADMIN");
        BtnSystemAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSystemAdminLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSystemAdminLogin);
        BtnSystemAdminLogin.setBounds(130, 480, 130, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(850, 320, 130, 160);

        BtnPatientLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnPatientLogin.setForeground(new java.awt.Color(0, 102, 153));
        BtnPatientLogin.setText("PATIENT");
        BtnPatientLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPatientLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPatientLogin);
        BtnPatientLogin.setBounds(850, 480, 130, 50);

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 102, 153));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setText("EXIT SYSTEM");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(560, 630, 190, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mrmbackground.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSystemAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSystemAdminLoginActionPerformed
        // TODO add your handling code here:
       SystemLogin rl=new SystemLogin();
       rl.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnSystemAdminLoginActionPerformed

    private void BtnHospitalAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHospitalAdminLoginActionPerformed
        // TODO add your handling code here:
       HospitalLogin rl=new HospitalLogin();
       rl.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnHospitalAdminLoginActionPerformed

    private void BtnCommunityAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCommunityAdminLoginActionPerformed
        // TODO add your handling code here:
       CommunityLogin rl=new CommunityLogin();
       rl.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnCommunityAdminLoginActionPerformed

    private void BtnPatientLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPatientLoginActionPerformed
        // TODO add your handling code here:
       PatientLogin rl=new PatientLogin();
       rl.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnPatientLoginActionPerformed

    private void BtnDoctorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoctorLoginActionPerformed
        // TODO add your handling code here:
       DoctorLogin rl=new DoctorLogin();
       rl.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnDoctorLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCommunityAdminLogin;
    private javax.swing.JButton BtnDoctorLogin;
    private javax.swing.JButton BtnHospitalAdminLogin;
    private javax.swing.JButton BtnPatientLogin;
    private javax.swing.JButton BtnSystemAdminLogin;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
